### ISSUE TITLE
predict.mfp with Cox models not working

### ISSUE THREAD

**Issue by matherealize** [georgheinze/mfp#3]
When using a Cox model the `predict.mfp()` function does not work as expected. 

Example: using the example code from the documentation of "mfp", there is an error:

```R
> data(GBSG)
> f <- mfp(Surv(rfst, cens) ~ fp(age, df = 4, select = 0.05) + fp(prm, df = 4, select = 0.05), family = cox, data = GBSG)
> predict(f)
Error in match.arg(type) : 
  'arg' should be one of “lp”, “risk”, “expected”, “terms”, “survival”
```

It does work with `predict(f$fit)`. This is only an issue with Cox models, for glms also `predict(f)` works fine. This can likely be solved by not using `getFromNameSpace` but using similar code as for glms in `predict.mfp`. Alternatively, the inteded usage could be documented for `predict.mfp()`.

**Comment by georgheinze** [comment]
'link' should return the predicted linear predictor in logistic regression, so if family="cox", the function should switch from type="link" to type="lp" to produce the linear predictor. The problem is that what is called 'link' in glm, is 'lp' in coxph.
