### ISSUE TITLE
predict.mfp does not return anything

### ISSUE THREAD

**Issue by matherealize** [georgheinze/mfp#4]
Another issue related with `predict.mfp()` - it does not return anything (NULL) when anything other than terms are requested.

I think the issue is because of the recent additions of the if statement `if (type == "terms")`. What happens is that if one wants to have predictions, they are created but never returned, as R returns the last output of the statements in the function, which happens to be NULL due to the if statement. 

A solution would be to explicity return the output.

**Comment by gregorsteiner** [comment]
I could not reproduce this, it works for me even if `type` is not `'terms'`. Do you have an example?

**Comment by georgheinze** [comment]
I found the same problem: predict(type="response") returns NULL, example easily created:
library(mfp)
x <- xorig <- runif(1000, min=-0.5, max=1.5)
y <- 5 + 3*x^2+rnorm(1000, 0, 1)
fit <- mfp(y~fp(x))
p<-predict(fit, type="response", newdata=data.frame(x=x))
p # NULL
pt <- predict(fit, type="terms", terms="x", seq=list(seq(-0.4, 0.4, 0.01)), ref=list(0))
pt # works
